{
  imports = [
    ./btop.nix
    ./firefox.nix
    ./git.nix
    ./helix.nix
    ./hyprlock.nix
    ./kitty.nix
    ./mullvad.nix
    ./networkmanager.nix
    ./ranger.nix
    ./standard.nix
    ./swaync.nix
    ./vscode.nix
    ./wireshark.nix
    ./wofi.nix
    ./xdg.nix
    ./zellij.nix
    ./zen-browser.nix
    ./shell.nix
  ];
}
